### ISSUE TITLE
Server won't start with node.js 4.1.1

### ISSUE THREAD

**Issue by ekkis** [Linkurious/linkurious.js#274]
I just upgraded to node.js 4.1.1 - now I can't get the server started.  below is the error I get (on OSX Yosemite).  I've removed the `node_modules` folder and performed the `npm install` to no avail.  what else can I do?

```
aprilis:linkurious.js ekkis$ node -v
v4.1.1
aprilis:linkurious.js ekkis$ npm start

> linkurious@1.1.0 start /Users/ekkis/Development/linkurious.js
> http-server -p 8000

events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE 0.0.0.0:8000
    at Object.exports._errnoException (util.js:837:11)
    at exports._exceptionWithHostPort (util.js:860:20)
    at Server._listen2 (net.js:1231:14)
    at listen (net.js:1267:10)
    at net.js:1376:9
    at doNTCallback3 (node.js:440:9)
    at process._tickCallback (node.js:346:17)
    at Function.Module.runMain (module.js:477:11)
    at startup (node.js:117:18)
    at node.js:951:3

npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v4.1.1
npm ERR! npm  v2.14.4
npm ERR! code ELIFECYCLE
npm ERR! linkurious@1.1.0 start: `http-server -p 8000`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the linkurious@1.1.0 start script 'http-server -p 8000'.
npm ERR! This is most likely a problem with the linkurious package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     http-server -p 8000
npm ERR! You can get their info via:
npm ERR!     npm owner ls linkurious
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/ekkis/Development/linkurious.js/npm-debug.log
```

**Comment by ekkis** [comment]
goodness me.  I must be tired.  it was failing because it was already running in a separate window.
