### ISSUE TITLE
Running in a NodeJs app?

### ISSUE THREAD

**Issue by ekkis** [Linkurious/linkurious.js#308]
I'm interested in using the library from a node.js application and I see that `src/sigma.export.js` seems to set it up.  in fact, I can do: `var sigma = require('sigma');` but if I try to call some function it fails, e.g. `sigma.neo4j.send()` returns:

sigma.neo4j.send();
           ^
TypeError: Cannot read property 'send' of undefined
    at Object.<anonymous> (/Users/ekkis/Development/UnionBank/dev/ui/tst.js:3:12)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:475:10)
    at startup (node.js:117:18)
    at node.js:951:3

so what am I missing?

**Comment by sheymann** [comment]
Hi, `sigma.export` does not contain any plugin.

**Comment by ekkis** [comment]
so if I need access to the plugins, what do I do?

**Comment by sheymann** [comment]
Will be fixed in next major release.
